namespace ZA_check.NoiseLw;

public class SecondData
{
    /*public int A { get; set; }
    public double AIR_VELOCITY { get; set; }
    public string ARTICLE_NO { get; set; }
    public int B2 { get; set; }
    public double CALC_AIR_DENSITY { get; set; }
    public int CALC_ALTITUDE { get; set; }
    public string CALC_LW5_OKT { get; set; }
    public string CALC_LW6_OKT { get; set; }
    public string CALC_LWA5_OKT { get; set; }
    public string CALC_LWA6_OKT { get; set; }
    public int CALC_NOZZLE_PRESSURE { get; set; }
    public int CALC_N_RATED { get; set; }
    public int CALC_PL_MAX { get; set; }
    public string CAPACITOR_CAPACITANCE { get; set; }
    public string CAPACITOR_VOLTAGE { get; set; }
    public string CHART_VIEWER_URL { get; set; }
    public string CIRCUIT { get; set; }
    public string COSPHI { get; set; }
    public string CURRENT_PHASE { get; set; }
    public int D1 { get; set; }
    public int D4 { get; set; }
    public int DA { get; set; }
    public int DD { get; set; }
    public string DENSITY_INFLUENCE { get; set; }
    public int DN { get; set; }
    public int DSA { get; set; }
    public string EC_TYPE { get; set; }
    public string EFFICIENCY_CLASS { get; set; }
    public string EFFICIENCY_STAT { get; set; }
    public string EFFICIENCY_TOT { get; set; }
    public string ERP_CLASS { get; set; }
    public int FAN_EFFICIENCY_GRADE { get; set; }
    public double FEI_FACTOR { get; set; }
    public string GRILL_INFLUENCE { get; set; }
    public int H { get; set; }
    public double H1 { get; set; }
    public double H5 { get; set; }
    public string IDCTEXT { get; set; }
    public string INCREASE_OF_CURRENT { get; set; }
    public int INSTALLATION_HEIGHT_MM { get; set; }
    public int INSTALLATION_LENGTH_MM { get; set; }
    public string INSTALLATION_POS { get; set; }
    public string INSTALLATION_POS_H { get; set; }
    public string INSTALLATION_POS_VO { get; set; }
    public string INSTALLATION_POS_VU { get; set; }
    public int INSTALLATION_WIDTH_MM { get; set; }
    public string IS_EC { get; set; }
    public string IS_VALID { get; set; }
    public int KFACTOR { get; set; }
    public int L { get; set; }
    public int L2 { get; set; }
    public int MAX_FREQUENCY { get; set; }
    public int MAX_TEMPERATURE_C { get; set; }
    public string MDRAWING { get; set; }
    public string MEASUREMENT_ID { get; set; }
    public int MIN_TEMPERATURE_C { get; set; }
    public string MOTOR_DESIGN { get; set; }
    public string MOTOR_IE_CLASS { get; set; }
    public int MOTOR_POLES { get; set; }
    public string MOTOR_SHAFT { get; set; }
    public string MOTOR_SIZE { get; set; }
    public double NOMINAL_CURRENT { get; set; }
    public string NOMINAL_FREQUENCY { get; set; }
    public double NOMINAL_IECMOTOR_EFFICIENCY { get; set; }
    public string NOMINAL_SPEED { get; set; }
    public int NOMINAL_VOLTAGE { get; set; }
    public string NOZZLE_GUARD { get; set; }
    public string NUMBER_OF_POLES { get; set; }
    public string PHASE_DIFFERENCE { get; set; }
    public double POWER_OUTPUT_KW { get; set; }
    public string PRODUCT_IMG { get; set; }
    public string PROTECTION_CLASS_IP { get; set; }
    public string PROTECTION_CLASS_THCL { get; set; }
    public int RUBBER_MOT_DIAMETER { get; set; }
    public int RUBBER_MOT_HEIGHT { get; set; }
    public int SPRING_MOT_DIAMETER { get; set; }
    public int SPRING_MOT_HEIGHT { get; set; }
    public int T { get; set; }
    public int T1 { get; set; }
    public int T3 { get; set; }
    public int T4 { get; set; }
    public int T5 { get; set; }
    public int T6 { get; set; }
    public double T7 { get; set; }
    public int T8 { get; set; }
    public string TYPE { get; set; }
    public string VOLTAGE_TOLERANCE { get; set; }
    public int ZAWALL_ARRANGEMENT { get; set; }
    public int ZA_BG { get; set; }
    public double ZA_COSPHI { get; set; }
    public double ZA_ETAF { get; set; }
    public double ZA_ETAF_L { get; set; }
    public double ZA_ETAF_L_MAINS_OPERATED { get; set; }
    public double ZA_ETAF_SYS { get; set; }
    public double ZA_ETAM { get; set; }
    public double ZA_ETASF { get; set; }
    public double ZA_ETASF_L { get; set; }
    public double ZA_ETASF_L_MAINS_OPERATED { get; set; }
    public double ZA_ETASF_SYS { get; set; }
    public int ZA_F { get; set; }
    public double ZA_FBP { get; set; }
    public int ZA_I { get; set; }
    public double ZA_IN { get; set; }
    public double ZA_LW5 { get; set; }
    public double ZA_LW6 { get; set; }
    public double ZA_LWA5 { get; set; }
    public double ZA_LWA6 { get; set; }
    public string ZA_MAINS_SUPPLY { get; set; }
    public double ZA_N { get; set; }
    public int ZA_NMAX { get; set; }
    public double ZA_P1 { get; set; }
    public double ZA_PD { get; set; }
    public double ZA_PF { get; set; }
    public double ZA_PF_MAINS_OPERATED { get; set; }
    public double ZA_PL { get; set; }
    public double ZA_PSF { get; set; }
    public double ZA_PSF_MAINS_OPERATED { get; set; }
    public double ZA_PSYS { get; set; }
    public double ZA_QV { get; set; }
    public double ZA_QV_MAINS_OPERATED { get; set; }
    public int ZA_SFP { get; set; }
    public int ZA_SFP_CLASS { get; set; }
    public int ZA_U { get; set; }
    public int ZA_UN { get; set; }
    public int ZA_WEIGHT { get; set; }
    public int dim_CG { get; set; }
    public int dim_DH { get; set; }
    public int dim_H { get; set; }
    public double dim_H1 { get; set; }
    public int dim_HB { get; set; }
    public double dim_HR { get; set; }
    public int dim_L { get; set; }
    public int dim_LF { get; set; }
    public int dim_LF2 { get; set; }
    public int dim_LM { get; set; }
    public double dim_LR { get; set; }
    public int dim_LS { get; set; }
    public int dim_LS1 { get; set; }
    public int dim_RL { get; set; }
    public int dim_RL1 { get; set; }
    public int dim_RL2 { get; set; }
    public int dim_RLB { get; set; }
    public int dim_RWD { get; set; }
    public int dim_RWE { get; set; }
    public int dim_RWE2 { get; set; }
    public int dim_RWN { get; set; }
    public int dim_RWS5 { get; set; }
    public int dim_W { get; set; }
    public int dim_W1 { get; set; }
    public int dim_WF { get; set; }
    public int dim_WS { get; set; }
    public int dim_b2 { get; set; }
    public int dim_d1 { get; set; }
    public int dim_dd { get; set; }
    public int dim_dn { get; set; }
    public int dim_dsa { get; set; }
    public int dim_dsa_2 { get; set; }
    public string dim_klischee { get; set; }*/
}
